language: R
cache: packages

r_packages:
    - covr

after_success:
    -Rscript -e "cov::codecov()"

before_cache: Rscript -e 'remotes::install_cran("pkgdown")'
deploy:
    provider: script
    script: Rscript -e 'pkgdown::deploy_site_github()'
    skip_cleanup: true
